### PR TITLE
feat: misc. updates for discovery network analysis

### PR DESCRIPTION
**Pull request by SionoiS**
# Description

I added more metrics to understand the discovery network better and a way to start without RLN.

I also created a new dashboard focused on discovery and changed the avg latency algo. to a smooth moving average.

# Changes

- [x] new dashboard
- [x] network monitor start without rln
- [x] network monitor cluster id metrics 
- [x] replace the avg latency algo.

### CODE REVIEW

**Review by gabrielmer — COMMENTED** [review]
Niice, thank you! Looks great 🤩 

Could you please add a screenshot of the new dashboard?

The linting check in the CI is failing, please have a look and if you think it can be an issue of the check itself lmk and I'll take care of it

**Comment by SionoiS** [comment]
Looks like this!
Screenshot from 2024-07-26 15-48-14

**Review by gabrielmer — APPROVED** [review]
Looks amazingg! 😍 

Thanks so much!

**Review by jm-clius — APPROVED** [review]
Looks pretty cool.

**Pull request merged**
